/**
 * Constantes de la aplicación.
 *
 * Regla: lo que no es secreto ni depende de la máquina vive acá.
 * Credenciales, rutas locales y el bucket viven en .env.
 */

/** Preferencias de la app, compartidas entre máquinas. */
export const SETTINGS_DOC = {
  collection: 'settings',
  docId: 'data-analizer',
} as const

/** Nodo de la Realtime Database con las sesiones abiertas. */
export const LIVE_SESSIONS_PATH = 'activeSessions'

/**
 * Toda la data en disco cuelga de una sola carpeta padre, separada del
 * código. Ops espeja acá las dos capas del bucket:
 *
 *   <Escritorio>/data-analizer-data/
 *     ├── raw-local-cache/       (espejo de raw/)
 *     └── bronze-local-cache/    (espejo de bronze/ + schemas/)
 *
 * (Las carpetas silver/gold-autogenerated que puedan convivir ahí son de la
 * generación local vieja: la transformación vive en BigQuery.)
 */
export const DATA_DIR_NAME = 'data-analizer-data'
export const CACHE_DIR_NAME = 'bronze-local-cache'
export const RAW_CACHE_DIR_NAME = 'raw-local-cache'

/** Las dos capas que Ops sincroniza y vigila. */
export type LayerId = 'raw' | 'bronze'
export const LAYERS: LayerId[] = ['raw', 'bronze']

/**
 * Registro del avance de cada sync en Firestore, un documento por capa.
 * Bronze conserva el docId histórico del espejo ('data-analizer'): la marca
 * de agua acumulada no se pierde al cambiar de app.
 */
export const SYNC_STATE_COLLECTION = 'sync_state'
export const SYNC_STATE_DOC_IDS: Record<LayerId, string> = {
  bronze: 'data-analizer',
  raw: 'data-analizer-raw',
}

/** Cada cuánto el vigía lista el bucket (hoy + ayer, por capa). */
export const WATCH_INTERVAL_MS = 60_000

/** Tope de entradas del log de Status (en memoria, derivado del listado). */
export const STATUS_FEED_LIMIT = 200

/** Filas que trae la tabla de eventos por consulta. */
export const EVENTS_PAGE_SIZE = 500

/**
 * El semáforo del ingestor: un probe TCP al puerto de ingest cada 5 minutos.
 * Conectar (aunque el servidor después conteste 400) prueba que la instancia
 * está levantada y escuchando — la definición pedida de "funciona".
 */
export const PING_INTERVAL_MS = 5 * 60_000
export const PING_TIMEOUT_MS = 5_000

/**
 * Frescura de cada capa, medida SOBRE LA CACHÉ LOCAL (cero requests): un
 * escaneo de disco por minuto. El punto de cada pestaña sale de acá.
 */
export const FRESHNESS_INTERVAL_MS = 60_000

/** Canales IPC entre el proceso main y el renderer. */
export const IPC = {
  eventsCatalog: 'events:catalog',
  settingsGet: 'settings:get',
  settingsSave: 'settings:save',
  liveSubscribe: 'live:subscribe',
  liveUnsubscribe: 'live:unsubscribe',
  liveSnapshot: 'live:snapshot',
  liveEvent: 'live:event',
  layerState: 'layer:state',
  layerSyncRun: 'layer:sync-run',
  layerSyncProgress: 'layer:sync-progress',
  schemaGet: 'schema:get',
  eventsQuery: 'events:query',
  rawQuery: 'raw:query',
  ingestSubscribe: 'ingest:subscribe',
  ingestUnsubscribe: 'ingest:unsubscribe',
  ingestStatus: 'ingest:status',
  freshnessSubscribe: 'freshness:subscribe',
  freshnessUnsubscribe: 'freshness:unsubscribe',
  freshnessSnapshot: 'freshness:snapshot',
  statusSubscribe: 'status:subscribe',
  statusUnsubscribe: 'status:unsubscribe',
  statusSnapshot: 'status:snapshot',
  billingGet: 'billing:get',
} as const
